### ISSUE TITLE
pyproject.toml support

### ISSUE THREAD

**Issue by parafoxia** [parafoxia/len8#18]
**Is your feature request related to a problem? Please describe.**
Having options set in the pyproject.toml like other tools do would be a huge plus.

**Describe the solution you'd like**
`[tool.len8]`

**Describe alternatives you've considered**
A .len8ignore file was considered, but deemed too unnecessary, especially as `mypy`'s .mypy.ini file, for example, is really annoying.

**Comment by Jonxslays** [comment]
An ideal implementation would look like:

```toml
[tool.len8]
# If no include specified the argument would be necessary on the cli (and in `Checker.check(...)`), but if they do specify include, we could make the path argument optional maybe?
include = ["path1", "path2"]
exclude = ["path3", "path4"]
code_length = 99
docs_length = 72
```

Would excludes just be accumulated between the `pyproject.toml` and the `.gitignore` when #17 is completed?
